# Generated by Django 4.2.7 on 2023-11-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('can_buy', models.BooleanField()),
                ('can_sell', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('diet_reqs', models.ManyToManyField(to='MealSharing.contains')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MealSharing.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('listed_date', models.DateField()),
                ('sell_by', models.DateField()),
                ('internal_id', models.CharField(max_length=40)),
                ('order_id', models.CharField(max_length=20)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to='MealSharing.user')),
                ('food_class', models.ManyToManyField(to='MealSharing.contains')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='MealSharing.user')),
            ],
        ),
    ]
