# Generated by Django 4.2.7 on 2023-11-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealSharing', '0004_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='order_id',
            new_name='order',
        ),
    ]
