# Generated by Django 4.2.7 on 2023-11-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealSharing', '0005_rename_order_id_meal_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='order',
        ),
        migrations.AddField(
            model_name='meal',
            name='number_listed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MealSharing.meal'),
        ),
    ]
